#!/usr/bin/env python3
"""Generate/check keys.mk and Android.bp from signing_profile.json."""
from __future__ import annotations
import argparse
from pathlib import Path
from signing_config import certificate_overrides, override_certificates

ROOT = Path(__file__).resolve().parent

def render_keys_mk() -> str:
    ovs = certificate_overrides()
    lines = [
        "# AUTO-GENERATED by generate_config.py. DO NOT EDIT MANUALLY.",
        "# PixelExperience/AOSP 13 private package-signing configuration.",
        "",
        "PRODUCT_CERTIFICATE_OVERRIDES := \\",
    ]
    for i, (module, cert) in enumerate(ovs):
        suffix = " \\" if i != len(ovs)-1 else ""
        lines.append(f"    {module}:{cert}{suffix}")
    lines += [
        "",
        "# Independent ROM release identity. For a NEW keyset releasekey must not",
        "# be a symlink to testkey. For an already-published keyset, preserve the",
        "# old identity until an intentional migration/rotation is planned.",
        "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/priv/keys/releasekey",
        "",
        "# Variable confirmed by the audited PE13 tree.",
        "PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := $(dir $(PRODUCT_DEFAULT_DEV_CERTIFICATE))",
        "",
        "# Do not blank PRODUCT_EXTRA_RECOVERY_KEYS here. The audited sargo product",
        "# uses recovery-as-boot, and leaving upstream/product policy untouched is",
        "# safer than globally clearing recovery/OTA trust material.",
        "",
    ]
    return "\n".join(lines)

def render_android_bp() -> str:
    lines = [
        "// AUTO-GENERATED by generate_config.py. DO NOT EDIT MANUALLY.",
        "// Private certificate modules referenced by PRODUCT_CERTIFICATE_OVERRIDES.",
        "",
    ]
    for cert in override_certificates():
        lines += [
            "android_app_certificate {",
            f'    name: "{cert}",',
            f'    certificate: "{cert}",',
            "}",
            "",
        ]
    return "\n".join(lines)

def check(path: Path, expected: str) -> bool:
    if not path.is_file():
        print(f"[FAIL] missing: {path}")
        return False
    if path.read_text(encoding="utf-8") != expected:
        print(f"[FAIL] generated file is stale: {path}")
        return False
    print(f"[OK]   {path.name}")
    return True

def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--print-certificates", action="store_true")
    args = ap.parse_args()
    if args.print_certificates:
        for cert in override_certificates():
            print(cert)
        return 0
    km = render_keys_mk()
    bp = render_android_bp()
    if args.write:
        (ROOT/"keys.mk").write_text(km, encoding="utf-8")
        (ROOT/"Android.bp").write_text(bp, encoding="utf-8")
        print("wrote keys.mk and Android.bp")
        return 0
    ok = check(ROOT/"keys.mk", km)
    ok = check(ROOT/"Android.bp", bp) and ok
    return 0 if ok else 1

if __name__ == "__main__":
    raise SystemExit(main())
