#!/usr/bin/env python3
"""Generate/check DeepDroid signing integration files from signing_profile.json."""
from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path

from signing_config import (
    certificate_overrides,
    active_override_certificates,
    extra_certificate_modules,
    override_certificates,
)

ROOT = Path(__file__).resolve().parent


def render_keys_mk() -> str:
    ovs = certificate_overrides()
    lines = [
        "# AUTO-GENERATED by ./keys.sh via generate_config.py. DO NOT EDIT MANUALLY.",
        "# DeepDroid private signing configuration.",
        "",
        "PRODUCT_CERTIFICATE_OVERRIDES := \\",
    ]
    for i, (module, cert) in enumerate(ovs):
        suffix = " \\" if i != len(ovs) - 1 else ""
        lines.append(f"    {module}:{cert}{suffix}")
    lines += [
        "",
        "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/priv/keys/releasekey",
        "",
        "# Variable confirmed by the audited DeepDroid tree.",
        "PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := $(dir $(PRODUCT_DEFAULT_DEV_CERTIFICATE))",
        "",
        "# Keep upstream/product recovery/OTA trust policy unless explicitly overridden.",
        "",
        "# Single DeepDroid signing entry point.",
        "-include vendor/priv/keys/BoardConfigPrivKeys.mk",
        "",
    ]
    return "\n".join(lines)


def render_android_bp() -> str:
    active = set(active_override_certificates())
    extras = set(extra_certificate_modules())
    lines = [
        "// AUTO-GENERATED by ./keys.sh via generate_config.py. DO NOT EDIT MANUALLY.",
        "// DeepDroid private certificate modules.",
        "",
    ]
    for cert in override_certificates():
        if cert in extras and cert not in active:
            lines.append("// Available compatibility certificate; not in current active mapping set.")
        lines += [
            "android_app_certificate {",
            f'    name: "{cert}",',
            f'    certificate: "{cert}",',
            "}",
            "",
        ]
    return "\n".join(lines)


def render_build_bazel() -> str:
    # Match the behavior of the older private-key template: expose generated
    # certificate/key files to Bazel when that target is consumed.
    return """# AUTO-GENERATED by ./keys.sh via generate_config.py. DO NOT EDIT MANUALLY.
filegroup(
    name = "android_certificate_directory",
    srcs = glob([
        "*.pk8",
        "*.pem",
    ]),
    visibility = ["//visibility:public"],
)
"""


def generated_files() -> dict[Path, str]:
    return {
        ROOT / "keys.mk": render_keys_mk(),
        ROOT / "Android.bp": render_android_bp(),
        ROOT / "BUILD.bazel": render_build_bazel(),
    }


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fp:
            fp.write(content)
            fp.flush()
            os.fsync(fp.fileno())
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def check(path: Path, expected: str) -> bool:
    if not path.is_file():
        print(f"[FAIL] missing generated file: {path.name}")
        return False
    if path.read_text(encoding="utf-8") != expected:
        print(f"[FAIL] generated file is stale: {path.name}")
        return False
    print(f"[OK]   {path.name}")
    return True


def profile_summary(prefix: str) -> None:
    print(
        f"{prefix}: mappings={len(certificate_overrides())} "
        f"active_certificates={len(active_override_certificates())} "
        f"available_certificate_modules={len(override_certificates())}"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--print-certificates", action="store_true",
                   help="print every certificate module that must have a key pair")
    g.add_argument("--print-active-certificates", action="store_true",
                   help="print only certificates referenced by active mappings")
    args = ap.parse_args()

    if args.print_certificates:
        for cert in override_certificates():
            print(cert)
        return 0
    if args.print_active_certificates:
        for cert in active_override_certificates():
            print(cert)
        return 0

    outputs = generated_files()
    if args.write:
        for path, content in outputs.items():
            atomic_write(path, content)
            print(f"[gen]  {path.name}")
        profile_summary("generated")
        return 0

    ok = True
    for path, content in outputs.items():
        ok = check(path, content) and ok
    if ok:
        profile_summary("profile")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
